# Generated by Django 4.2.4 on 2023-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbokingapp', '0003_tcktbooking_delete_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinghistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('count', models.IntegerField()),
                ('bookedtime', models.DateTimeField()),
            ],
        ),
    ]
