# Generated by Django 4.2.4 on 2023-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concertbokingapp', '0004_bookinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('artist', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('availticket', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='concerts',
        ),
    ]
